lab_name: TAN LAB
tagline: From basic neuroimmunology to engineering
intro: |
  We seek to understand the fundamental principles underlying gut inflammation and
  disease progression across space and time through developing interdisciplinary technologies
  and computational methodologies, and to design molecular switches and allosteric
  perturbations to study biological processes and the quantitative consequences at
  single-cell and systems level.


  ![](/assets/images/home-page-logo.png)

copyright: Copyright @ 2022 Tan Lab of Enteric neuroimmunology and Optogenetics
pi_github: https://github.com/tanlab1
home_hero_image: https://static.wixstatic.com/media/d8287f_0e49b76980534dde9b8fa21eca252854~mv2.png
research_hero_image: https://static.wixstatic.com/media/d8287f_4b92be91e3f8469394b3ca53be2bbe09~mv2.png
research_highlight_image: https://static.wixstatic.com/media/d8287f_d7001f5cc6124f70b78a04c09dd8bed7~mv2.webp
research_framework_image: /assets/images/research-overview.jpg
resources_hero_image: https://static.wixstatic.com/media/d8287f_0bf679b3f41c4316a646eb88a86f13df~mv2.png
publications_scholar_image: https://static.wixstatic.com/media/d8287f_eb0b97eac74340b6a096878f331ef999~mv2.png
